language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
    - ~/.npm
notifications:
  email: false
cache:
  directories:
    - node_modules
  yarn: true
node_js:
  - '8'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/
  target-branch: master
  github_token: $GH_TOKEN
  on:
    branch: v4
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
